FROM node:20 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable

WORKDIR /usr/src/app
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist /usr/src/app/dist
COPY ./tls /etc/nginx/ssl

EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
