networks:
  pong-network:
    driver: bridge

services:
  backend:
    build: ./backend
    networks:
      - pong-network
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: "file:./dev.db"

  frontend:
    build: ./frontend
    networks:
      - pong-network
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
 
volumes:
  db:

