networks:
  pong-network:
    driver: bridge

services:
  backend:
    build: ./backend
    networks:
      - pong-network
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env # Load environment variables from file
    volumes:
      - ./backend:/app
      - ./tls:/app/tls
      - /app/node_modules
    environment:
      - TLS_PATH=/app/tls
      - NODE_TLS_REJECT_UNAUTHORIZED=0 # Allow self-signed certificates for development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    networks:
      - pong-network
    ports:
      - '5173:5173'
    env_file:
      - ./frontend/.env # Load environment variables from file
    volumes:
      - ./frontend:/app
      - ./tls:/app/tls
      - /app/node_modules
    environment:
      - TLS_PATH=/app/tls
      - NODE_TLS_REJECT_UNAUTHORIZED=0 # Allow self-signed certificates for development
    depends_on:
      - backend

  ngrok:
    build: ./ngrok
    container_name: ngrok
    env_file: ./ngrok/.env
    environment:
      - APP_MODE=dev
    depends_on:
      - frontend
      - backend
    ports:
      - "4040:4040"
    networks:
      - pong-network