networks:
  pong-network:
    driver: bridge

services:
  backend:
    build: ./backend
    networks:
      - pong-network
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - ./tls:/app/tls
      - /app/node_modules
    environment:
      - TLS_PATH=/app/tls

  frontend:
    build: ./frontend
    networks:
      - pong-network
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - ./tls:/app/tls
      - /app/node_modules
    environment:
      - TLS_PATH=/app/tls
    command: npm run dev

  ngrok:
    build: ./ngrok
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: ["http", "https://host.docker.internal:5173"]
    depends_on:
      - frontend
    ports:
      - "4040:4040"
    networks:
      - pong-network
    extra_hosts:
      - "host.docker.internal:host-gateway"